# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Objective-C-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Push'
  # Pods for Objective-C-iOS

  target 'Objective-C-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Objective-C-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
